version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  test:
    description: Setup and run application tests
    executor:
      name: windows/default
    steps:
      - run:
          name: Configure Git User Info
    command: |
      git config --global user.email "${{ secrets.GITHUBEMAIL }}"
      git config --global user.name "${{ secrets.GITHUBUSERNAME }}"
      git add .
      git commit -m "Adding Latest Junit Report file"
      git config --global pull.ff only 
      git push origin HEAD:master --force

    steps:  
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "SampleProject.csproj" }}
      - run:
          name: "Run Application Tests"
          command: dotnet.exe test "SampleProject.csproj" --no-build --verbosity normal --logger:"junit;LogFilePath=test-result.xml"
          
      - store_artifacts:
          path: C:\Users\circleci\project\test-result.xml
