version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  test:
    description: Setup and run application tests
    executor: ubuntu-executor
    steps:
      - checkout
    - run:
          name: "Run Application Tests"
          command: dotnet test
