version: 2.1
orbs:
  jira: circleci/jira@2.1.0
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Restore dependencies
          command: dotnet restore
      - run:
          name: Run tests
          command: dotnet test "SampleProject.csproj" --no-build --verbosity normal --logger:"junit;LogFilePath=test-result.xml"
          
      - store_artifacts:
          path: test-result.xml
          destination: junit
      - store_test_results:
          path: test-result.xml

