name: Connect Github with BehavePro1

on: push
  
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
        - uses: actions/checkout@v4
            
        - name: Install dependencies
          run: dotnet restore
                   
        - name: Test with dotnet test
          run: dotnet test "SampleProject.csproj" --no-build --verbosity normal

        - name: Upload dotnet test results
          uses: actions/upload-artifact@v4
          with:
            name: dotnet-results-${{ matrix.dotnet-version }}
            path: "bin/Debug/net6.0/TestExecution.json"

        - name: git action adding test report
          run: |
               git config --global user.email "${{ secrets.GITHUBEMAIL }}"
               git config --global user.name "${{ secrets.GITHUBUSERNAME }}"
               git add .
               git commit -m "Adding latest specflow json report"
               git config --global pull.ff only 
               git push origin HEAD:master --force  

        - name: Posting report to jira with BehavePro
          run: |
               curl -L -X PUT https://test-reports.behave.pro/REST/1.0/bdd/report \
               -H "X-API-KEY: ${{ secrets.BEHAVEPROAPIKEY }}" \
               -H "X-COMMIT-ID: ${ github.sha }" \
               --data-binary @bin/Debug/net6.0/TestExecution.json
          
