name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
        - uses: actions/checkout@v4
        - name: Setup .NET 6.x
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '6.x'
        - name: Install dependencies
          run: dotnet restore
        - name: Test with dotnet test
          run: dotnet test "SampleProject.csproj" --no-build --verbosity normal --logger:"junit;LogFilePath=test-result.xml"
        - name: Upload dotnet test results
          uses: actions/upload-artifact@v3
          with:
            name: dotnet-results-${{ matrix.dotnet-version }}
            path: "test-result.xml"
          # Use always() to always run this step to publish test results when there are test failures
          if: ${{ always() }}
        - name: Parse_Results
          run: for file in $( find  -type f -name "*.xml")
           for file in $( find  -type f -name "*.xml")
           do
             echo -e "Working on file -----------------------------------> $file"
             Parser_Response=$(curl --request POST https://pulse-13.qtestnet.com/webhook/9c276f29-0b44-43bd-9363-b4bc436f57c5 -d projectId="9655" -d testcycle="55152" -d "result=$(echo $(cat $file) | basenc --base64url | tr -d \\n)" )             
           done 
