name: SpecflowJsonReportTest

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
        - uses: actions/checkout@v4
        
        - name: Setup .NET 6.x
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '6.x'
            
        - name: Install dependencies
          run: dotnet restore
          
        - name: Test with dotnet test
          run: dotnet test --configuration Release --logger:trx;LogFileName=test_results.trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura

        - name: Generate SpecFlow JSON Report
          run: dotnet specflow generateall --format=json
          working-directory: /home/runner/work/SampleProject/SampleProject/TestResults/

        - name: Upload SpecFlow JSON Report
          uses: actions/upload-artifact@v3
          with:
            name: specflow-json-report
            path: ./path/to/specflow/project/*.json
