name: SpecflowLivingDocHTMLReports

on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        packages: write
    strategy:
          matrix:
           dotnet-version: [ '6.0.x' ]

    steps:
        - uses: actions/checkout@v4
        - name: Setup .NET 6.x
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '6.x'
        - name: Install dependencies
          run: dotnet restore
          
        - name: Test with dotnet test
          run: dotnet test "SampleProject.csproj" --no-build --verbosity normal

        - name: create html living doc report from json
          run: |
                dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
                livingdoc feature-folder "Features" -t "bin/Debug/net6.0/TestExecution.json"  

        - name: git action adding test report
          run: |
               git config --global user.email "${{ secrets.GITHUBEMAIL }}"
               git config --global user.name "${{ secrets.GITHUBUSERNAME }}"
               git add "LivingDoc.html"
               git commit -m "adding latest emailable reports"
               git config --global pull.ff only 
               git push origin HEAD:master --force 

        - name: Living Doc HTML Reports
          uses: actions/upload-artifact@v4
          with:
              name: LivingDocHTML
              path: "LivingDoc.html"  
