name: SpecflowLivingDocHTML

on: [push]
  #pull_request:
   # types:
     # - opened
     # - synchronize
  
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
        - uses: actions/checkout@v4
        - name: Setup .NET 6.x
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '6.x'
        - name: Install dependencies
          run: dotnet restore
          
        - name: Test with dotnet test
          run: dotnet test "SampleProject.csproj" --no-build --verbosity normal
          
        - name: Upload Results JSON
          uses: actions/upload-artifact@v4
          with:
              name: JSONTestResults
              path: "bin/Debug/net6.0/TestExecution.json"

        - name: create html living doc report from json
          run: |
                dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
                livingdoc feature-folder "Features" -t "bin/Debug/net6.0/TestExecution.json"  

        - name: Living Doc HTML Reports
          uses: actions/upload-artifact@v4
          with:
              name: LivingDocHTML
              path: "LivingDoc.html"
                

